package sait.bms.problemdoamin;

public class Paperback extends Book {

	private String author;
	private int year;
	private String genre;
	private final String genreA = "Adventure";
	private final String genreD = "Drama";
	private final String genreE = "Education";
	private final String genreC = "Classic";
	private final String genreF = "Fantasy";
	private final String genreS = "Science Fiction";
	

	public Paperback() {
		super();
		// TODO Autogenerated constructor stub
	}

	public Paperback(String isbn, String callNumber, int available, int total, String title, String author, int year,
			String genre) {
		super(isbn, callNumber, available, total, title);
		this.author = author;
		this.year = year;
		this.genre = genre;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	/**
	 * Convert abbreviation letters into words 
	 */
	@Override
	public String toString() {
		
		switch (getGenre()) {
		case "A": {
			genre = genreA;
			break;
		}
		case "D": {
			genre = genreD;
			break;
		}
		case "E": {
			genre = genreE;
			break;
		}
		case "C": {
			genre = genreC;
			break;
		}
		case "F": {
			genre = genreF;
			break;
		}
		case "S": {
			genre = genreS;
			break;
		}
		}

		return String.format("%-18s%s\n%-18s%s\n%-18s%s\n%-18s%s\n%-18s%s\n%-18s%s\n%-18s%s\n%-18s%s\n", "ISBN:",
				getIsbn(), "Call Number:", getCallNumber(), "Available:", Integer.toString(getAvailable()), "Total:",
				Integer.toString(getTotal()), "Title:", getTitle(), "Author:", getAuthor(), "Year:", getYear(),
				"Genre:", genre);
	}

}
